version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
        - 3306:3306
    volumes:
        - db-store:/var/lib/mysql

volumes:
  db-store:
